require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'cortellisMobile' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'cortellisMobileTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'cortellisMobile-tvOS' do
  # Pods for cortellisMobile-tvOS

  target 'cortellisMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
